# Generated by Django 5.2.6 on 2025-10-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRIAL', 'Trial'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='INACTIVE', help_text='Current subscription status of this business', max_length=20),
        ),
    ]
