# Generated by Django 5.2.6 on 2025-10-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_preferences_and_2fa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmembership',
            name='rbac_role',
            field=models.ForeignKey(blank=True, help_text='RBAC role for permission management', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_memberships', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_format',
            field=models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='24h', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Africa/Accra', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
