# Generated by Django 5.2.6 on 2025-10-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_link_membership_rbac_roles'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessmembership',
            constraint=models.UniqueConstraint(fields=('user',), name='one_user_one_business', violation_error_message='A user can only belong to one business. This email is already registered with another business.'),
        ),
    ]
