# Generated by Django 5.2.6 on 2025-10-07 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regional', models.JSONField(blank=True, default=dict, help_text='Regional settings including currency, timezone, and number formats')),
                ('appearance', models.JSONField(blank=True, default=dict, help_text='Visual appearance settings including theme and display options')),
                ('notifications', models.JSONField(blank=True, default=dict, help_text='Notification preferences for email, SMS, and push notifications')),
                ('receipt', models.JSONField(blank=True, default=dict, help_text='Receipt printing and display preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(help_text='The business these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
                'db_table': 'business_settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
