# Generated by Django 5.2.6 on 2025-09-30 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockproduct',
            new_name='stock_produ_stock_i_e22ecb_idx',
            old_name='stock_stock_i_7df94b_idx',
        ),
        migrations.RenameIndex(
            model_name='stockproduct',
            new_name='stock_produ_product_667705_idx',
            old_name='stock_product_117577_idx',
        ),
        migrations.RenameIndex(
            model_name='stockproduct',
            new_name='stock_produ_supplie_d6b389_idx',
            old_name='stock_supplie_a23fb0_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.supplier'),
        ),
        migrations.AlterModelTable(
            name='stockproduct',
            table='stock_products',
        ),
    ]
