# Generated by Django 5.2.6 on 2025-09-28 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_businessmembership'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStoreFront',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_storefronts', to='accounts.business')),
                ('storefront', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_link', to='inventory.storefront')),
            ],
            options={
                'db_table': 'business_storefronts',
                'ordering': ['business__name', 'storefront__name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_warehouses', to='accounts.business')),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_link', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'business_warehouses',
                'ordering': ['business__name', 'warehouse__name'],
            },
        ),
        migrations.CreateModel(
            name='StoreFrontEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_employees', to='accounts.business')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.storefront')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefront_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storefront_employees',
                'ordering': ['storefront__name', 'user__name'],
                'unique_together': {('storefront', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_employees', to='accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_assignments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'warehouse_employees',
                'ordering': ['warehouse__name', 'user__name'],
                'unique_together': {('warehouse', 'user')},
            },
        ),
    ]
