# Generated by Django 5.2.6 on 2025-09-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_stock_stock_i_7df94b_idx_stock_produ_stock_i_e22ecb_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stock',
            new_name='stock_warehou_7a5d57_idx',
            old_name='stock_batch_warehou_72bf35_idx',
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse'),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
