# Generated by Django 5.2.6 on 2025-09-28 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_businessstorefront_businesswarehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
                'ordering': ['product__name', 'warehouse__name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='batch',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='batchproduct',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchproduct',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_batch_i_e0b9ab_idx',
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='inventory.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'warehouse', 'stock')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['stock', 'warehouse'], name='inventory_stock_i_fbc2c8_idx'),
        ),
        migrations.DeleteModel(
            name='BatchProduct',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse', 'product'], name='stock_warehou_983938_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'expiry_date'], name='stock_product_117577_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['reference_code'], name='stock_referen_c146b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product', 'reference_code', 'expiry_date'), name='stock_unique_reference'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='batch',
        ),
    ]
