# Generated by Django 5.2.6 on 2025-09-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_remove_batch_warehouse_and_more'),
        ('sales', '0002_remove_saleitem_sales_items_product_16c0be_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
