# Generated by Django 5.2.6 on 2025-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_stock_batch_warehou_72bf35_idx_stock_warehou_7a5d57_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockproduct',
            name='stock_unique_product_supplier_expiry',
        ),
        migrations.AddIndex(
            model_name='stockproduct',
            index=models.Index(fields=['stock', 'product', 'unit_cost'], name='stock_produ_stock_i_f83768_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockproduct',
            constraint=models.UniqueConstraint(fields=('stock', 'product', 'supplier', 'expiry_date', 'unit_cost'), name='stock_unique_product_supplier_expiry_cost'),
        ),
    ]
