# Generated by Django 5.2.6 on 2025-10-02 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_platform_role'),
        ('inventory', '0010_transfer_workflow_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferauditentry',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('UPDATED', 'Updated'), ('RECEIPT_CONFIRMED', 'Receipt confirmed')], max_length=20),
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('linked_transfer_reference', models.CharField(blank=True, max_length=32, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='accounts.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='inventory.storefront')),
            ],
            options={
                'db_table': 'transfer_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='inventory.transferrequest'),
        ),
        migrations.CreateModel(
            name='TransferRequestLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_request_line_items', to='inventory.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inventory.transferrequest')),
            ],
            options={
                'db_table': 'transfer_request_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['business', 'status'], name='transfer_re_busines_a40a46_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['storefront', 'status'], name='transfer_re_storefr_2dc0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequestlineitem',
            index=models.Index(fields=['request'], name='transfer_re_request_151e26_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequestlineitem',
            index=models.Index(fields=['product'], name='transfer_re_product_93cb07_idx'),
        ),
    ]
