# Generated by Django 5.2.6 on 2025-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockadjustment_stockadjustmentdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='quantity_before',
            field=models.IntegerField(blank=True, help_text='Stock product quantity before this adjustment (snapshot at creation)', null=True),
        ),
    ]
