# Generated by Django 5.2.6 on 2025-10-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_stock_integrity_constraints'),
        ('inventory', '0014_add_quantity_before_to_stock_adjustment'),
    ]

    operations = [
    ]
