# Generated by Django 5.2.6 on 2025-10-10 13:17

import django.db.models.deletion
from django.db import migrations, models


def migrate_warehouse_to_stock_product(apps, schema_editor):
    """Copy warehouse from Stock to all related StockProduct records"""
    Stock = apps.get_model('inventory', 'Stock')
    StockProduct = apps.get_model('inventory', 'StockProduct')
    
    for stock in Stock.objects.all():
        # Update all StockProduct records that belong to this stock batch
        StockProduct.objects.filter(stock=stock).update(warehouse=stock.warehouse)


def reverse_warehouse_migration(apps, schema_editor):
    """No reverse migration needed - data remains in StockProduct"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_merge_20251010_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'ordering': ['product__name', 'warehouse__name']},
        ),
        migrations.RemoveConstraint(
            model_name='stockproduct',
            name='stock_product_quantity_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='storefrontinventory',
            name='storefront_inventory_quantity_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='storefrontinventory',
            name='unique_storefront_product',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='stock_warehou_7a5d57_idx',
        ),
        # Add warehouse field to StockProduct (nullable first)
        migrations.AddField(
            model_name='stockproduct',
            name='warehouse',
            field=models.ForeignKey(
                null=True,  # Temporarily nullable for data migration
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='stock_products', 
                to='inventory.warehouse'
            ),
        ),
        # Migrate data from Stock.warehouse to StockProduct.warehouse
        migrations.RunPython(
            migrate_warehouse_to_stock_product,
            reverse_warehouse_migration
        ),
        # Make warehouse field non-nullable
        migrations.AlterField(
            model_name='stockproduct',
            name='warehouse',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stock_products',
                to='inventory.warehouse'
            ),
        ),
        # Remove warehouse from Stock
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['arrival_date'], name='stock_arrival_5d189a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockproduct',
            index=models.Index(fields=['warehouse', 'product'], name='stock_produ_warehou_792818_idx'),
        ),
    ]
