# Generated by Django 5.2.6 on 2025-10-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_move_warehouse_to_stock_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
