# Generated by Django 5.2.6 on 2025-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_inventory_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferauditentry',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='related_transfer',
        ),
        migrations.RemoveField(
            model_name='transferlineitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='transferauditentry',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='transferlineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='linked_transfer_reference',
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=16),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='TransferAuditEntry',
        ),
        migrations.DeleteModel(
            name='TransferLineItem',
        ),
    ]
