# Generated by Django 5.2.6 on 2025-10-27 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_link_membership_rbac_roles'),
        ('inventory', '0021_make_stock_business_non_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=16),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('W2W', 'Warehouse to Warehouse'), ('W2S', 'Warehouse to Storefront')], db_index=True, max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reference_number', models.CharField(db_index=True, help_text='Auto-generated if not provided: TRF-YYYYMMDDHHMMSS', max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.business')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_storefront', models.ForeignKey(blank=True, help_text='For W2S transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='inventory.storefront')),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='For W2W transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='inventory.warehouse')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Quantity to transfer')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (auto-detected from source if not provided)', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Calculated: quantity * unit_cost', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transfer')),
            ],
            options={
                'db_table': 'inventory_transfer_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['business', 'status'], name='inventory_t_busines_c2ea0f_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['business', 'created_at'], name='inventory_t_busines_f0836e_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['source_warehouse', 'status'], name='inventory_t_source__a49ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['destination_warehouse', 'status'], name='inventory_t_destina_e99efe_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['reference_number'], name='inventory_t_referen_6e93f6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferitem',
            index=models.Index(fields=['transfer', 'product'], name='inventory_t_transfe_ef8cf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'product'), name='unique_product_per_transfer'),
        ),
    ]
