# Generated by Django 5.2.6 on 2025-10-27 03:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_add_transfer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='expected_arrival_date',
            field=models.DateField(blank=True, help_text='Expected arrival date at destination', null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiration date for perishable items', null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retail selling price', max_digits=12),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Original supplier (copied from source stock)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='unit_additional_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Additional costs per unit (shipping, handling, etc.)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='unit_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Tax amount per unit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='unit_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Tax rate percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wholesale selling price', max_digits=12),
        ),
    ]
