# Generated by Django 5.2.6 on 2025-10-27 03:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_add_stock_batch_fields_to_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated: quantity * unit_cost', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transferitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (auto-detected from source if not provided)', max_digits=10, null=True),
        ),
    ]
