# Generated by Django 5.2.6 on 2025-10-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_make_unit_cost_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='linked_transfer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='linked_transfer_reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
