# Generated by Django 5.2.6 on 2025-10-12 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportNotificationSettings',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='export_notification_settings', serialize=False, to='accounts.business')),
                ('notify_on_success', models.BooleanField(default=True, help_text='Send email when scheduled export succeeds')),
                ('notify_on_failure', models.BooleanField(default=True, help_text='Send email when scheduled export fails')),
                ('default_recipients', models.JSONField(blank=True, default=list, help_text='Default email recipients for all exports')),
                ('from_name', models.CharField(blank=True, help_text="Custom 'from' name for export emails", max_length=100)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Reply-to email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'export_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='ExportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this schedule', max_length=255)),
                ('export_type', models.CharField(choices=[('SALES', 'Sales Export'), ('CUSTOMERS', 'Customer Export'), ('INVENTORY', 'Inventory Export'), ('AUDIT_LOGS', 'Audit Logs Export')], max_length=20)),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='excel', max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('hour', models.IntegerField(default=2, help_text='Hour of day to run (0-23, UTC)')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly exports (0=Monday)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly exports (1-28)', null=True)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send exports to')),
                ('include_creator_email', models.BooleanField(default=True, help_text="Include the schedule creator's email in recipients")),
                ('email_subject', models.CharField(blank=True, help_text='Custom email subject (optional)', max_length=255)),
                ('email_message', models.TextField(blank=True, help_text='Custom email message (optional)')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Export-specific filters (date ranges, customer types, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_schedules', to='accounts.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=10)),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('API', 'API')], default='MANUAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EMAILED', 'Emailed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to stored file (S3, local, etc.)', max_length=500)),
                ('record_count', models.IntegerField(blank=True, help_text='Number of records exported', null=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Filters used for this export')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses that received this export')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to='accounts.business')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the export (null for scheduled)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_history', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, help_text='Associated schedule (null for manual exports)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.exportschedule')),
            ],
            options={
                'verbose_name_plural': 'Export histories',
                'db_table': 'export_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exportschedule',
            index=models.Index(fields=['business', 'is_active'], name='export_sche_busines_b8d6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='exportschedule',
            index=models.Index(fields=['next_run_at'], name='export_sche_next_ru_47dd21_idx'),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['business', 'created_at'], name='export_hist_busines_05af78_idx'),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['schedule', 'status'], name='export_hist_schedul_daf1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='exporthistory',
            index=models.Index(fields=['user', 'created_at'], name='export_hist_user_id_40e270_idx'),
        ),
    ]
