# Generated by Django 5.2.6 on 2025-11-02 12:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Number of this payment attempt (1 for first attempt)'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base subscription price before taxes and charges', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Human-readable failure reason'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='gateway_error_code',
            field=models.CharField(blank=True, help_text='Error code from payment gateway', max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='gateway_error_message',
            field=models.TextField(blank=True, help_text='Error message from payment gateway'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='previous_attempt',
            field=models.ForeignKey(blank=True, help_text='Link to previous failed attempt if this is a retry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='subscriptions.subscriptionpayment'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='pricing_tier_snapshot',
            field=models.JSONField(default=dict, help_text='Snapshot of pricing tier configuration used for this payment'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='service_charges_breakdown',
            field=models.JSONField(default=dict, help_text='\n        Service charges: {\n            "payment_gateway": {"type": "PERCENTAGE", "rate": 2.00, "amount": "3.60"}\n        }\n        '),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='status_history',
            field=models.JSONField(default=list, help_text='\n        Payment status history: [\n            {"status": "PENDING", "timestamp": "2024-01-01T10:00:00Z"},\n            {"status": "FAILED", "timestamp": "2024-01-01T10:05:00Z", "reason": "..."}\n        ]\n        '),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='storefront_count',
            field=models.IntegerField(default=1, help_text='Number of storefronts at time of payment'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='tax_breakdown',
            field=models.JSONField(default=dict, help_text='\n        Tax breakdown: {\n            "VAT": {"rate": 15.00, "amount": "27.00"},\n            "NHIL": {"rate": 2.50, "amount": "4.50"}\n        }\n        '),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='total_service_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('charge_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of amount'), ('FIXED', 'Fixed amount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='For PERCENTAGE: rate as percentage (e.g., 2.00 for 2%). For FIXED: absolute amount.', max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('applies_to', models.CharField(choices=[('SUBTOTAL', 'Subtotal (before tax)'), ('TOTAL', 'Total (after tax)')], default='SUBTOTAL', max_length=20)),
                ('payment_gateway', models.CharField(choices=[('ALL', 'All gateways'), ('PAYSTACK', 'Paystack only'), ('STRIPE', 'Stripe only'), ('MOMO', 'Mobile Money only')], default='ALL', help_text='Which payment gateways this charge applies to', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_charge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPricingTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_storefronts', models.IntegerField(help_text='Minimum number of storefronts for this tier (inclusive)')),
                ('max_storefronts', models.IntegerField(blank=True, help_text='Maximum number of storefronts (inclusive). NULL means unlimited.', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this tier in the specified currency', max_digits=10)),
                ('price_per_additional_storefront', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per storefront beyond min_storefronts. Used for open-ended tiers.', max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Only active tiers are used for pricing calculation')),
                ('description', models.TextField(blank=True, help_text='Internal notes about this tier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pricing_tiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Pricing Tier',
                'verbose_name_plural': 'Subscription Pricing Tiers',
                'db_table': 'subscription_pricing_tier',
                'ordering': ['min_storefronts'],
                'indexes': [models.Index(fields=['is_active', 'min_storefronts'], name='subscriptio_is_acti_20121c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_storefronts__gte', models.F('min_storefronts')), ('max_storefronts__isnull', True), _connector='OR'), name='max_storefronts_gte_min_storefronts')],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Tax name (e.g., 'VAT', 'NHIL', 'GETFund Levy')", max_length=100)),
                ('code', models.CharField(help_text="Unique code (e.g., 'VAT_GH', 'NHIL_GH')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 15.00 for 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('country', models.CharField(default='GH', help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('applies_to_subscriptions', models.BooleanField(default=True, help_text='Whether this tax applies to subscription payments')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this tax must be applied (cannot be opted out)')),
                ('calculation_order', models.IntegerField(default=0, help_text='Order in which tax is calculated (lower numbers first)')),
                ('applies_to', models.CharField(choices=[('SUBTOTAL', 'Subtotal (before other taxes)'), ('CUMULATIVE', 'Cumulative (including previous taxes)')], default='SUBTOTAL', help_text='What amount to apply the tax to', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(help_text='Date from which this tax rate is effective')),
                ('effective_until', models.DateField(blank=True, help_text='Date until which this tax rate is effective (NULL = indefinite)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
                'db_table': 'tax_configuration',
                'ordering': ['calculation_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'effective_from', 'effective_until'], name='tax_configu_is_acti_b5a419_idx'), models.Index(fields=['country', 'is_active'], name='tax_configu_country_888ff7_idx')],
            },
        ),
    ]
