# Generated by Django 5.2.6 on 2025-11-03 18:00

from django.db import migrations
from decimal import Decimal
from datetime import date


def populate_pricing_tiers(apps, schema_editor):
    """Populate subscription pricing tiers and tax configurations"""
    SubscriptionPricingTier = apps.get_model('subscriptions', 'SubscriptionPricingTier')
    TaxConfiguration = apps.get_model('subscriptions', 'TaxConfiguration')
    
    # Create Pricing Tiers (if they don't exist)
    tiers_data = [
        {
            'min_storefronts': 1,
            'max_storefronts': 1,
            'base_price': Decimal('100.00'),
            'price_per_additional_storefront': Decimal('0.00'),
            'currency': 'GHS',
            'is_active': True,
            'description': 'Tier for 1 storefront'
        },
        {
            'min_storefronts': 2,
            'max_storefronts': 2,
            'base_price': Decimal('150.00'),
            'price_per_additional_storefront': Decimal('0.00'),
            'currency': 'GHS',
            'is_active': True,
            'description': 'Tier for 2 storefronts'
        },
        {
            'min_storefronts': 3,
            'max_storefronts': 3,
            'base_price': Decimal('180.00'),
            'price_per_additional_storefront': Decimal('0.00'),
            'currency': 'GHS',
            'is_active': True,
            'description': 'Tier for 3 storefronts'
        },
        {
            'min_storefronts': 4,
            'max_storefronts': 4,
            'base_price': Decimal('200.00'),
            'price_per_additional_storefront': Decimal('0.00'),
            'currency': 'GHS',
            'is_active': True,
            'description': 'Tier for 4 storefronts'
        },
        {
            'min_storefronts': 5,
            'max_storefronts': None,
            'base_price': Decimal('200.00'),
            'price_per_additional_storefront': Decimal('50.00'),
            'currency': 'GHS',
            'is_active': True,
            'description': 'Tier for 5+ storefronts (base + per additional)'
        },
    ]
    
    for tier_data in tiers_data:
        SubscriptionPricingTier.objects.get_or_create(
            min_storefronts=tier_data['min_storefronts'],
            max_storefronts=tier_data['max_storefronts'],
            defaults=tier_data
        )
    
    # Create Tax Configurations (if they don't exist)
    taxes_data = [
        {
            'code': 'VAT_GH',
            'name': 'VAT',
            'rate': Decimal('3.00'),
            'country': 'GH',
            'applies_to_subscriptions': True,
            'is_active': True,
            'calculation_order': 1,
            'effective_from': date(2024, 1, 1),
            'description': 'Value Added Tax (Ghana)',
            'applies_to': 'SUBTOTAL',
            'is_mandatory': True
        },
        {
            'code': 'NHIL_GH',
            'name': 'NHIL',
            'rate': Decimal('2.50'),
            'country': 'GH',
            'applies_to_subscriptions': True,
            'is_active': True,
            'calculation_order': 2,
            'effective_from': date(2024, 1, 1),
            'description': 'National Health Insurance Levy (Ghana)',
            'applies_to': 'SUBTOTAL',
            'is_mandatory': True
        },
        {
            'code': 'GETFUND_GH',
            'name': 'GETFund Levy',
            'rate': Decimal('2.50'),
            'country': 'GH',
            'applies_to_subscriptions': True,
            'is_active': True,
            'calculation_order': 3,
            'effective_from': date(2024, 1, 1),
            'description': 'Ghana Education Trust Fund Levy',
            'applies_to': 'SUBTOTAL',
            'is_mandatory': True
        },
        {
            'code': 'COVID19_GH',
            'name': 'COVID-19 Health Recovery Levy',
            'rate': Decimal('1.00'),
            'country': 'GH',
            'applies_to_subscriptions': True,
            'is_active': True,
            'calculation_order': 4,
            'effective_from': date(2024, 1, 1),
            'description': 'COVID-19 Health Recovery Levy (Ghana)',
            'applies_to': 'SUBTOTAL',
            'is_mandatory': True
        },
    ]
    
    for tax_data in taxes_data:
        TaxConfiguration.objects.get_or_create(
            code=tax_data['code'],
            defaults=tax_data
        )


def reverse_populate(apps, schema_editor):
    """Reverse migration - delete created pricing tiers and tax configs"""
    SubscriptionPricingTier = apps.get_model('subscriptions', 'SubscriptionPricingTier')
    TaxConfiguration = apps.get_model('subscriptions', 'TaxConfiguration')
    
    # Delete the pricing tiers we created
    SubscriptionPricingTier.objects.filter(
        min_storefronts__in=[1, 2, 3, 4, 5],
        currency='GHS'
    ).delete()
    
    # Delete the tax configurations we created
    TaxConfiguration.objects.filter(
        code__in=['VAT_GH', 'NHIL_GH', 'GETFUND_GH', 'COVID19_GH']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionpayment_attempt_number_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_pricing_tiers, reverse_populate),
    ]
