# Generated by Django 5.2.6 on 2025-11-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Deprecate the old SubscriptionPlan model in favor of SubscriptionPricingTier.
    
    This migration:
    1. Makes the 'plan' field nullable on Subscription model
    2. Adds a warning note that SubscriptionPlan is deprecated
    
    Future migration will remove SubscriptionPlan entirely after data cleanup.
    """

    dependencies = [
        ('subscriptions', '0003_populate_pricing_tiers'),
    ]

    operations = [
        # Make plan field nullable and optional
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='subscriptions',
                to='subscriptions.subscriptionplan',
                help_text='DEPRECATED: Use SubscriptionPricingTier instead'
            ),
        ),
    ]
