# Generated by Django 5.2.6 on 2025-11-26 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramBlueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "summary",
                    models.TextField(
                        help_text="Short description shown on program cards"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("owner_department", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("support_link", models.URLField(blank=True)),
                ("consent_text", models.TextField(blank=True)),
                ("application_notes", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("default_badges", models.JSONField(blank=True, default=list)),
                (
                    "highlights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Key bullet points for marketing copy",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("allow_waitlist", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programs_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "program_blueprints",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ProgramCohort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("OPEN", "Open"),
                            ("PAUSED", "Paused"),
                            ("CLOSED", "Closed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("badges", models.JSONField(blank=True, default=list)),
                ("capacity_total", models.PositiveIntegerField(default=0)),
                ("confirmed_applicants", models.PositiveIntegerField(default=0)),
                ("waitlist_enabled", models.BooleanField(default=False)),
                (
                    "waitlist_capacity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("application_open_date", models.DateField(blank=True, null=True)),
                ("application_close_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.CharField(blank=True, max_length=255)),
                ("application_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_cohorts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="programs.programblueprint",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="program_cohorts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "program_cohorts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramDocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IDENTIFICATION", "Identification"),
                            ("BUSINESS", "Business"),
                            ("FINANCIAL", "Financial"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=50,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "applies_before_selection",
                    models.BooleanField(
                        default=True,
                        help_text="If true, applicants must upload before selecting the cohort",
                    ),
                ),
                (
                    "upload_key",
                    models.CharField(
                        help_text="Frontend key used to map uploads to storage buckets",
                        max_length=120,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="programs.programcohort",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="programs.programblueprint",
                    ),
                ),
            ],
            options={
                "db_table": "program_document_requirements",
                "ordering": ["program", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramEligibilityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("LOCATION", "Location"),
                            ("BUSINESS_SIZE", "Business size"),
                            ("EXPERIENCE", "Experience"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Machine readable rule definition",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="programs.programcohort",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="programs.programblueprint",
                    ),
                ),
            ],
            options={
                "db_table": "program_eligibility_rules",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ProgramPackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("unit_label", models.CharField(blank=True, max_length=50)),
                ("badge", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="programs.programblueprint",
                    ),
                ),
            ],
            options={
                "db_table": "program_package_items",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ProgramReferralChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_channels",
                        to="programs.programblueprint",
                    ),
                ),
            ],
            options={
                "db_table": "program_referral_channels",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.AddIndex(
            model_name="programcohort",
            index=models.Index(
                fields=["status", "application_close_date"],
                name="program_coh_status_096beb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programcohort",
            index=models.Index(
                fields=["program", "status"], name="program_coh_program_caa511_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programreferralchannel",
            unique_together={("program", "label")},
        ),
    ]
