# Generated by Django 5.2.6 on 2025-11-07 10:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_one_user_one_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_balance', 'Low Balance'), ('depleted', 'Depleted'), ('expired', 'Expired')], max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to='accounts.business')),
            ],
            options={
                'verbose_name': 'AI Usage Alert',
                'verbose_name_plural': 'AI Usage Alerts',
                'db_table': 'ai_usage_alerts',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AICreditPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credits_purchased', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonus_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus credits for bulk purchases', max_digits=10)),
                ('payment_reference', models.CharField(help_text='Payment gateway reference', max_length=255, unique=True)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('free_trial', 'Free Trial'), ('admin_grant', 'Admin Grant')], max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_purchases', to='accounts.business')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Credit Purchase',
                'verbose_name_plural': 'AI Credit Purchases',
                'db_table': 'ai_credit_purchases',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['business', '-purchased_at'], name='ai_credit_p_busines_bdbaf6_idx'), models.Index(fields=['payment_status'], name='ai_credit_p_payment_6cc1e8_idx'), models.Index(fields=['payment_reference'], name='ai_credit_p_payment_019aaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AITransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('credit_assessment', 'Credit Risk Assessment'), ('collection_priority', 'Collection Priority Analysis'), ('collection_message', 'Collection Message Generator'), ('portfolio_dashboard', 'Portfolio Health Dashboard'), ('payment_prediction', 'Payment Prediction'), ('customer_insight', 'Customer Insight Query'), ('natural_language_query', 'Natural Language Query'), ('product_description', 'Product Description Generator'), ('report_narrative', 'Report AI Narrative'), ('inventory_forecast', 'Inventory Forecasting')], help_text='AI feature that was used', max_length=50)),
                ('credits_used', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_to_us', models.DecimalField(decimal_places=4, help_text='Actual OpenAI API cost in GHS', max_digits=6)),
                ('tokens_used', models.IntegerField(default=0, help_text='Total tokens used (input + output)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_data', models.JSONField(default=dict, help_text='Store request parameters (for debugging)')),
                ('response_summary', models.TextField(blank=True, help_text='Brief summary of AI response')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Time taken to process request in milliseconds')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_transactions', to='accounts.business')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the AI request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Transaction',
                'verbose_name_plural': 'AI Transactions',
                'db_table': 'ai_transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['business', 'feature', '-timestamp'], name='ai_transact_busines_3fcd6d_idx'), models.Index(fields=['business', 'success'], name='ai_transact_busines_e1df72_idx'), models.Index(fields=['-timestamp'], name='ai_transact_timesta_5007a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessAICredits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current AI credit balance', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Credits expire date (typically 6 months from purchase)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these credits are still valid')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credits', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Business AI Credits',
                'verbose_name_plural': 'Business AI Credits',
                'db_table': 'business_ai_credits',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='business_ai_busines_4e9f0f_idx'), models.Index(fields=['expires_at'], name='business_ai_expires_197ce7_idx')],
            },
        ),
    ]
