# Generated by Django 5.2.6 on 2025-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicreditpurchase',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Payment gateway response data including tax breakdown'),
        ),
    ]
