# Generated by Django 5.2.6 on 2025-09-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_remove_batch_warehouse_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='saleitem',
            name='sales_items_product_16c0be_idx',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='batch',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.stock'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product', 'stock'], name='sales_items_product_603c5c_idx'),
        ),
    ]
