# Generated by Django 5.2.6 on 2025-10-01 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_make_tax_fields_nullable'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='stock_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.stockproduct'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product', 'stock_product'], name='sales_items_product_443222_idx'),
        ),
    ]
