# Generated by Django 5.2.6 on 2025-10-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auditlog_stockreservation_customer_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
