# Generated by Django 5.2.6 on 2025-10-09 08:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20251003_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount refunded to the customer', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
