# Generated by Django 5.2.6 on 2025-10-15 18:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_amount_refunded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_credit_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this sale is on credit (AR), False for cash/card/mobile payments'),
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original credit amount', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=10)),
                ('amount_outstanding', models.DecimalField(decimal_places=2, help_text='Remaining balance', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('WRITTEN_OFF', 'Written Off'), ('IN_COLLECTION', 'In Collection')], db_index=True, default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, help_text='Expected payment date', null=True)),
                ('days_outstanding', models.IntegerField(db_index=True, default=0, help_text='Days since sale created')),
                ('aging_category', models.CharField(choices=[('CURRENT', '0-30 days'), ('30_DAYS', '31-60 days'), ('60_DAYS', '61-90 days'), ('90_PLUS', '90+ days')], db_index=True, default='CURRENT', max_length=20)),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Collection agent assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ar', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ar', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='sales.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Accounts Receivable',
                'verbose_name_plural': 'Accounts Receivable',
                'db_table': 'accounts_receivable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check')], db_index=True, max_length=20)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts_receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_payments', to='sales.accountsreceivable')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_ar_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AR Payment',
                'verbose_name_plural': 'AR Payments',
                'db_table': 'ar_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['customer', 'status'], name='accounts_re_custome_67a155_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['status', 'aging_category'], name='accounts_re_status_9a700c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['due_date'], name='accounts_re_due_dat_383366_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['days_outstanding'], name='accounts_re_days_ou_d2f53e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['assigned_to', 'status'], name='accounts_re_assigne_5e5da4_idx'),
        ),
        migrations.AddIndex(
            model_name='arpayment',
            index=models.Index(fields=['accounts_receivable', 'payment_date'], name='ar_payments_account_dac2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='arpayment',
            index=models.Index(fields=['payment_method', 'payment_date'], name='ar_payments_payment_e7c6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='arpayment',
            index=models.Index(fields=['received_by', 'payment_date'], name='ar_payments_receive_15c041_idx'),
        ),
    ]
